version: '3.8'

volumes:
  database-data:


networks:
  net-serverless:


services:
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - ${DATABASE_PORT}:5432
    expose:
      - ${DATABASE_PORT}
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - net-serverless

  adminer:
    image: adminer
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=database
    networks:
      - net-serverless
