service: serverless-example

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  users:
    environment:
      NODE_ENV: ${env:NODE_ENV}
      DATABASE_TYPE: ${env:DATABASE_TYPE}
      DATABASE_HOST: ${env:DATABASE_HOST}
      DATABASE_PORT: ${env:DATABASE_PORT}
      DATABASE_LOGGING: ${env:DATABASE_LOGGING}
      DATABASE_NAME: ${env:DATABASE_NAME}
      DATABASE_USERNAME: ${env:DATABASE_USERNAME}
      DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
      DATABASE_SSL: ${env:DATABASE_SSL}
    timeout: 60
    memorySize: 1024
    handler: dist/apps/users/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
